name: Bazel CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bazelisk
        run: |
          curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -o bazel
          chmod +x bazel
          sudo mv bazel /usr/local/bin/bazel

      - name: Verify Bazel
        run: bazel version

      - name: Build project
        run: bazel build //app:calculator_app

      - name: Run tests
        run: bazel test //app:math_test
